import fs from 'fs-extra';
import { join } from 'path';
import ora from 'ora';
import chalk from 'chalk';
import { log, section } from '../ui/logger.js';
import { AIProvider } from '../ai/provider.js';

export class TemplateEngine {
  constructor(projectDir = process.cwd()) {
    this.projectDir = projectDir;
    this.templatesDir = join(new URL('../../templates', import.meta.url).pathname);
  }

  async generateHealthCheck(runtime = 'node') {
    section('Health Check Generator');
    const templates = {
      node: `// Health check endpoint — generated by dnpm
import os from 'os';

export function healthCheck(req, res) {
  const health = {
    status: 'ok',
    timestamp: new Date().toISOString(),
    uptime: process.uptime(),
    memory: {
      used: Math.round(process.memoryUsage().heapUsed / 1024 / 1024) + 'MB',
      total: Math.round(os.totalmem() / 1024 / 1024) + 'MB',
    },
    cpu: os.loadavg(),
    pid: process.pid,
    version: process.env.npm_package_version || '1.0.0',
  };

  try {
    // Add your DB health check here
    // await db.query('SELECT 1');
    res.status(200).json(health);
  } catch (err) {
    health.status = 'error';
    health.error = err.message;
    res.status(503).json(health);
  }
}

// Express route: app.get('/health', healthCheck);
`,
      python: `# Health check endpoint — generated by dnpm
import os
import time
import psutil
from flask import jsonify

start_time = time.time()

def health_check():
    """Health check endpoint"""
    memory = psutil.virtual_memory()
    health = {
        "status": "ok",
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "uptime": round(time.time() - start_time),
        "memory": {
            "used": f"{memory.used // (1024*1024)}MB",
            "total": f"{memory.total // (1024*1024)}MB",
            "percent": memory.percent,
        },
        "cpu": psutil.cpu_percent(),
        "pid": os.getpid(),
    }

    try:
        # Add your DB health check here
        return jsonify(health), 200
    except Exception as e:
        health["status"] = "error"
        health["error"] = str(e)
        return jsonify(health), 503

# Flask route: @app.route('/health')
`,
      go: `// Health check endpoint — generated by dnpm
package main

import (
	"encoding/json"
	"net/http"
	"os"
	"runtime"
	"time"
)

var startTime = time.Now()

type HealthResponse struct {
	Status    string            \`json:"status"\`
	Timestamp string            \`json:"timestamp"\`
	Uptime    string            \`json:"uptime"\`
	Memory    map[string]string \`json:"memory"\`
	GoRoutines int             \`json:"goroutines"\`
	PID       int              \`json:"pid"\`
}

func healthCheckHandler(w http.ResponseWriter, r *http.Request) {
	var m runtime.MemStats
	runtime.ReadMemStats(&m)

	health := HealthResponse{
		Status:    "ok",
		Timestamp: time.Now().UTC().Format(time.RFC3339),
		Uptime:    time.Since(startTime).String(),
		Memory: map[string]string{
			"alloc":      formatBytes(m.Alloc),
			"totalAlloc": formatBytes(m.TotalAlloc),
			"sys":        formatBytes(m.Sys),
		},
		GoRoutines: runtime.NumGoroutine(),
		PID:       os.Getpid(),
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(health)
}

func formatBytes(b uint64) string {
	const unit = 1024
	if b < unit {
		return fmt.Sprintf("%d B", b)
	}
	div, exp := uint64(unit), 0
	for n := b / unit; n >= unit; n /= unit {
		div *= unit
		exp++
	}
	return fmt.Sprintf("%.1f %cB", float64(b)/float64(div), "KMGTPE"[exp])
}

// Usage: http.HandleFunc("/health", healthCheckHandler)
`,
    };

    const code = templates[runtime] || templates.node;
    const ext = runtime === 'python' ? 'py' : runtime === 'go' ? 'go' : 'js';
    const filePath = join(this.projectDir, `health.${ext}`);
    await fs.writeFile(filePath, code);
    log(`Health check generated: health.${ext}`, 'success');
    return filePath;
  }

  async scaffoldProject(runtime = 'node', options = {}) {
    section('Project Scaffold');
    const spinner = ora(`Scaffolding ${runtime} project...`).start();

    const scaffolders = {
      node: () => this._scaffoldNode(options),
      python: () => this._scaffoldPython(options),
      go: () => this._scaffoldGo(options),
    };

    const scaffolder = scaffolders[runtime];
    if (!scaffolder) throw new Error(`Unsupported scaffold runtime: ${runtime}`);
    await scaffolder();
    spinner.succeed(`${runtime} project scaffolded`);
  }

  async _scaffoldNode(options = {}) {
    const dir = this.projectDir;
    await fs.ensureDir(join(dir, 'src'));
    await fs.ensureDir(join(dir, 'tests'));

    // package.json
    if (!await fs.pathExists(join(dir, 'package.json'))) {
      await fs.writeJson(join(dir, 'package.json'), {
        name: options.name || 'app',
        version: '1.0.0',
        type: 'module',
        main: 'src/index.js',
        scripts: {
          start: 'node src/index.js',
          dev: 'node --watch src/index.js',
          test: 'node --test tests/',
          build: 'echo "No build step"',
        },
        dependencies: {},
      }, { spaces: 2 });
    }

    // Main server
    await fs.writeFile(join(dir, 'src', 'index.js'), `import http from 'http';

const PORT = process.env.PORT || 3000;

const server = http.createServer((req, res) => {
  if (req.url === '/health') {
    res.writeHead(200, { 'Content-Type': 'application/json' });
    return res.end(JSON.stringify({
      status: 'ok',
      uptime: process.uptime(),
      timestamp: new Date().toISOString(),
    }));
  }

  res.writeHead(200, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify({ message: 'Hello from dnpm!' }));
});

server.listen(PORT, () => {
  console.log(\`Server running on port \${PORT}\`);
});
`);

    // Test
    await fs.writeFile(join(dir, 'tests', 'health.test.js'), `import { describe, it } from 'node:test';
import assert from 'node:assert';

describe('Health Check', () => {
  it('should return ok', async () => {
    const res = await fetch('http://localhost:3000/health');
    const data = await res.json();
    assert.strictEqual(data.status, 'ok');
  });
});
`);
  }

  async _scaffoldPython(options = {}) {
    const dir = this.projectDir;
    await fs.ensureDir(join(dir, 'app'));
    await fs.ensureDir(join(dir, 'tests'));

    await fs.writeFile(join(dir, 'requirements.txt'), `flask==3.0.0
gunicorn==21.2.0
psutil==5.9.7
`);

    await fs.writeFile(join(dir, 'app', '__init__.py'), '');
    await fs.writeFile(join(dir, 'app', 'main.py'), `from flask import Flask, jsonify
import time
import os

app = Flask(__name__)
start_time = time.time()

@app.route('/')
def index():
    return jsonify({"message": "Hello from dnpm!"})

@app.route('/health')
def health():
    return jsonify({
        "status": "ok",
        "uptime": round(time.time() - start_time),
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    })

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 8000))
    app.run(host='0.0.0.0', port=port)
`);
  }

  async _scaffoldGo(options = {}) {
    const dir = this.projectDir;
    await fs.writeFile(join(dir, 'main.go'), `package main

import (
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"time"
)

var startTime = time.Now()

func main() {
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(map[string]string{"message": "Hello from dnpm!"})
	})

	http.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(map[string]interface{}{
			"status":    "ok",
			"uptime":    time.Since(startTime).String(),
			"timestamp": time.Now().UTC().Format(time.RFC3339),
		})
	})

	fmt.Printf("Server running on port %s\\n", port)
	http.ListenAndServe(":"+port, nil)
}
`);
  }

  async aiGenerate(description) {
    section('AI Template Generator');
    try {
      const ai = await AIProvider.create();
      const code = await ai.generateCode(description);
      console.log(`\n${code}\n`);
      return code;
    } catch (err) {
      log(`AI generation failed: ${err.message}`, 'error');
    }
  }
}
